request:
    resource: "@RequestBundle/Resources/config/routing.yml"
    prefix:   /

extranet:
    resource: "@ExtranetBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


# app/config/routing.yml
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
admin:
      resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
      prefix:   /admin/
_sonata_admin:
      resource: .
      type:     sonata_admin
      prefix:   /admin/
sonata_user:
     resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
     prefix: /admin/
estatica:
    pattern:  /nosotros/{pagina}/
    defaults: { _controller: FrontBundle:Sitio:estatica }
login:
    pattern: /login/
    defaults: { _controller: FrontBundle:Sitio:login }
login_check:
    pattern:   /extranet/login_check/
logout:
    pattern:   /logout/
mail:
    pattern:  /sucess/
    defaults: { _controller: FrontBundle:Sitio:mail }
portada:
    pattern:  /
    defaults: { _controller: FrontBundle:Sitio:home }