parameters:
#    request.example.class: Alood\RequestBundle\Example

services:
#    request.example:
#        class: %request.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
