<?php

namespace Alood\BackBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Alood\BackBundle\Controller\AdminController();
        return $instance;
    }
}
