<?php

namespace Alood\FrontBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SitioController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Alood\FrontBundle\Controller\SitioController();
        return $instance;
    }
}
