<?php

namespace Proxies\__CG__\Alood\ExtranetBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Fabricante extends \Alood\ExtranetBundle\Entity\Fabricante implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["usuario"];
        }
        $this->__load();
        return parent::getUsuario();
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getProductos()
    {
        $this->__load();
        return parent::getProductos();
    }

    public function setUsuario($item)
    {
        $this->__load();
        return parent::setUsuario($item);
    }

    public function setNombre($item)
    {
        $this->__load();
        return parent::setNombre($item);
    }

    public function setEmail($item)
    {
        $this->__load();
        return parent::setEmail($item);
    }

    public function setTelefono($item)
    {
        $this->__load();
        return parent::setTelefono($item);
    }

    public function setPassword($item)
    {
        $this->__load();
        return parent::setPassword($item);
    }

    public function setProductos($item)
    {
        $this->__load();
        return parent::setProductos($item);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'usuario', 'nombre', 'password', 'email', 'telefono', 'productos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}