<?php

namespace Proxies\__CG__\Alood\BackBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Usuario extends \Alood\BackBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getUser()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["user"];
        }
        $this->__load();
        return parent::getUser();
    }

    public function getAlergenos()
    {
        $this->__load();
        return parent::getAlergenos();
    }

    public function getComentarios()
    {
        $this->__load();
        return parent::getComentarios();
    }

    public function setEmail($item)
    {
        $this->__load();
        return parent::setEmail($item);
    }

    public function setPassword($item)
    {
        $this->__load();
        return parent::setPassword($item);
    }

    public function setUser($item)
    {
        $this->__load();
        return parent::setUser($item);
    }

    public function setAlergenos($item)
    {
        $this->__load();
        return parent::setAlergenos($item);
    }

    public function setComentarios($item)
    {
        $this->__load();
        return parent::setComentarios($item);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'user', 'email', 'password', 'alergenos', 'comentarios');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}