parameters:
#    extranet.example.class: Alood\ExtranetBundle\Example

#    extranet.example:
#        class: %extranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
      login_listener:
          class: Alood\ExtranetBundle\Listener\LoginListener
          arguments: [@router]
          tags:
             - { name: kernel.event_listener, event: security.interactive_login }
             - { name: kernel.event_listener, event: kernel.response }